# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y --no-install-recommends build-essential mercurial python-lxml python-setuptools libffi-dev python-pip python-dev libzmq3-dev python-pandas graphviz libssl-dev python-zmq python-kerberos git
     sudo pip install graphviz functools32 jupyter tornado

     ## GateOne Install
     git clone --depth=1 https://github.com/liftoff/GateOne
     cd GateOne
     sudo python setup.py install
     cd ..

     ## GateOne Setup
     sudo mkdir -p /etc/gateone/conf.d
     wget https://bitbucket.org/nbastin/geni-lib/raw/20160122-cn4421/support/gateone.conf
     sudo cp gateone.conf /etc/gateone/conf.d/60local.conf

     ## geni-lib install
     hg clone http://bitbucket.org/barnstorm/geni-lib
     cd geni-lib
     hg update -C 0.9-DEV
     sudo python setup.py install

     ## geni-lib setup
     if [ -f /vagrant/omni.bundle ]
        then
          echo "/vagrant/omni.bundle exists. Configuring geni-lib."
          PARMS=(--bundle /vagrant/omni.bundle)
          if [ -f /vagrant/cert.key ]
             then
                PARMS+=(--cert-private-key /vagrant/cert.key)
          fi
          if [ -f /vagrant/ssh.pubkey ]
             then
                PARMS+=(--pubkey /vagrant/ssh.pubkey)
          fi
          sudo -u vagrant /usr/local/bin/context-from-bundle "${PARMS[@]}"
     fi
     mkdir -p ~/notebooks
     mkdir -p ~/.ipython/extensions
     cp tools/ipython/genish.py ~/.ipython/extensions
     sudo cp support/jupyter-upstart /etc/init/jupyter.conf
     sudo start jupyter
     sudo service start gateone
  SHELL

end
